<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leaveType_excludeIfNoEntitlement_CHECKBOX</name>
   <tag></tag>
   <elementGuidId>c90e4eef-99b8-4cd7-9cde-5b02c99f8c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;leaveType_excludeIfNoEntitlement&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
